### ISSUE TITLE
feat: 可用设备列表与自定义连接的 ADB 

### ISSUE THREAD

**Issue by bakashigure** [MaaAssistantArknights/MaaAsstElectronUI#16]
`Windows`: 左侧可用设备列表使用模拟器自带的`adb`，右侧自定义连接使用下载的`adb`
`Linux` | `macOS`: 左侧可用设备列表和自定义连接均使用下载的 `adb`

可以在 UI 第一次打开的时候把 `adb` 和 `core` 一起下载。

- [x] 自动下载 `adb`
- [x] `Windows` 左侧设备列表
- [x] `Windows` 右侧自定义连接
- [x] #52
- [x] `Linux` 右侧自定义连接
- [x] `macOS` 左侧设备列表
- [x] `macOS` 右侧自定义连接

**Comment by ChingCdesu** [comment]
adb下载需要MaaDS支持

**Comment by ChingCdesu** [comment]
v2仅仅制作windows版本
