### ISSUE TITLE
模拟器连接问题

### ISSUE THREAD

**Issue by qiutongxue** [MaaAssistantArknights/MaaAsstElectronUI#34]
https://github.com/MaaAssistantArknights/MaaAsstElectronUI/blob/8aaa64b1c9692871b30b76c2807dd13be2f39ba7/packages/main/hooks/emulator.ts#L162

如果 `adb_path` 带有空格的话（如 `E:/Program Files/Nox/...`），Powershell 就比较傻，以为 E:/Program 和 Files/Nox/ 是两个东西，所以可能要改成

```js
  const exp = `& '${e.adb_path}' devices`;
```

但是我不清楚 Linux 会不会有这个问题。。

---

另外获取不到 uuid（夜神模拟器），`service call iphonesubinfo 1` 输出的是下面这玩意（真的就是 8 个点..）

```
Result: Parcel(00000000 ffffffff   '........')
```

https://github.com/MaaAssistantArknights/MaaAsstElectronUI/blob/8aaa64b1c9692871b30b76c2807dd13be2f39ba7/packages/main/hooks/emulator.ts#L290-L295

**Comment by bakashigure** [comment]
感谢 issue !
https://github.com/MaaAssistantArknights/MaaAsstElectronUI/blob/72f3a8d2d88b8ae402b502818294e39a5257c5d5/packages/main/core/emulator/shell.ts#L14
`windows` 下现在默认改成 `& `作为命令前缀；  
`Linux` 下目前暂未测试。

---

在 https://github.com/MaaAssistantArknights/MaaAsstElectronUI/commit/018b9652a962783a7469d3f0dc36d93d3403bf3a 中更改了获取`uuid`的方式，经过测试，蓝叠、逍遥、夜神 这三个模拟器均可以正常获取到。

**Comment by qiutongxue** [comment]
https://github.com/MaaAssistantArknights/MaaAsstElectronUI/blob/37ee8c506dbed3686622ae1612a2e55dc7aa0ffd/packages/main/deviceDetector/winAdapter.ts#L192

和

https://github.com/MaaAssistantArknights/MaaAsstElectronUI/blob/37ee8c506dbed3686622ae1612a2e55dc7aa0ffd/packages/main/deviceDetector/winAdapter.ts#L216

漏了引号，因改成：

```ts
[...(await $`"${e.adb_path}" devices`).stdout.matchAll(regExp)] 
```
