### ISSUE TITLE
环境配置失败

### ISSUE THREAD

**Issue by yltx** [MaaAssistantArknights/MaaAsstElectronUI#39]
如题  折腾了挺长时间 结果就这样了……
PS E:\MaaAsstElectronUI> yarn
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 373ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 5s 518ms
➤ YN0000: ┌ Link step
➤ YN0007: │ electron@npm:17.1.2 must be built because it never has been before or the last one failed
➤ YN0007: │ ref-napi@npm:3.0.3 must be built because it never has been before or the last one failed
➤ YN0007: │ @seorii/win32-displayconfig@npm:0.1.1 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.14.27 must be built because it never has been before or the last one failed
➤ YN0007: │ vue-demi@npm:0.12.4 [4f0a8] must be built because it never has been before or the last one failed
➤ YN0007: │ es5-ext@npm:0.10.59 must be built because it never has been before or the last one failed
➤ YN0009: │ es5-ext@npm:0.10.59 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\yltx\AppData\Local\Temp\xfs-3aa34e92\build.log)
➤ YN0009: │ electron@npm:17.1.2 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\yltx\AppData\Local\Temp\xfs-1d9e7e59\build.log)
➤ YN0009: │ esbuild@npm:0.14.27 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\yltx\AppData\Local\Temp\xfs-f40c5451\build.log)
➤ YN0009: │ ref-napi@npm:3.0.3 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\yltx\AppData\Local\Temp\xfs-1a17aedd\build.log)
➤ YN0009: │ vue-demi@npm:0.12.4 [4f0a8] couldn't be built successfully (exit code 1, logs can be found here: C:\Users\yltx\AppData\Local\Temp\xfs-864ba569\build.log)
➤ YN0009: │ @seorii/win32-displayconfig@npm:0.1.1 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\yltx\AppData\Local\Temp\xfs-c677d184\build.log)
➤ YN0007: │ electron-acrylic-window@npm:0.5.11 must be built because it never has been before or the last one failed
➤ YN0007: │ ffi-napi@npm:4.0.3 must be built because it never has been before or the last one failed
➤ YN0009: │ electron-acrylic-window@npm:0.5.11 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\yltx\AppData\Local\Temp\xfs-166c50b5\build.log)
➤ YN0009: │ ffi-napi@npm:4.0.3 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\yltx\AppData\Local\Temp\xfs-c322350b\build.log)
➤ YN0000: └ Completed in 15s 467ms
➤ YN0000: Failed with errors in 21s 523ms

**Comment by ChingCdesu** [comment]
可能装依赖的时候需要visual studio，我自己是原来就装了vs，所以没试过没装vs下的情况

我的环境：
node 16
yarn v1
visual studio 2022

**Comment by bakashigure** [comment]
我的环境同上，`node`版本高于16时打包会失败。
`node-gyp` 还需要`python3`作为依赖。

**Comment by yltx** [comment]
> 可能装依赖的时候需要visual studio，我自己是原来就装了vs，所以没试过没装vs下的情况
> 
> 我的环境： node 16 yarn v1 visual studio 2022

问题是我也有vs啊

**Comment by yltx** [comment]
> 我的环境同上，`node`版本高于16时打包会失败。 `node-gyp` 还需要`python3`作为依赖。

我是node v17.1.0
yarn v1.22.15

**Comment by ChingCdesu** [comment]
node-gyp和node 17确实有兼容性问题，和electron ffi-napi的兼容性问题还未解决。所以我们降级成node16了
https://github.com/nodejs/node-gyp/issues/2543

**Comment by yltx** [comment]
> 

淦  但是我自己还有项目啊  完全不想降级啊

**Comment by ChingCdesu** [comment]
> 淦 但是我自己还有项目啊 完全不想降级啊
考虑使用一下虚拟环境

**Comment by bakashigure** [comment]
有没有可能 node 也有版本管理工具

**Comment by bakashigure** [comment]
在`windows`上可以使用`nvm`进行`node`的版本管理。不过这可能并不能对解决你的问题提供帮助，我更认为是你本地的环境有问题，~~在我这里能跑啊~~。

**Comment by yltx** [comment]
> 在`windows`上可以使用`nvm`进行`node`的版本管理。不过这可能并不能对解决你的问题提供帮助，我更认为是你本地的环境有问题，~在我这里能跑啊~。

我本地的环境已经修过一次了  不修的话输npm、node、yarn都识别不出来是命令

**Comment by yltx** [comment]
> > 淦 但是我自己还有项目啊 完全不想降级啊
> 
> 考虑使用一下虚拟环境，可能有帮助（

用了  然后我wsl环境也寄了
