### ISSUE TITLE
关卡选择

### ISSUE THREAD

**Issue by bakashigure** [MaaAssistantArknights/MaaAsstElectronUI#43]
目前支持的关卡是硬编码在代码中，大概长这样
```
      levels: [
        {
          code: 'CE-6', // 龙门币
          times: 0
        },
        {
          code: 'AP-5', // 红票
          times: 0
        },
        {
          code: 'CA-5', // 技能书
          times: 0
        },
        {
          code: 'LS-6', // 作 战 记 录
          times: 0
        },
        {
          code: '1-7', // 1 - 7 // BUG!
          times: 0
        },
        {
          code: 'SN-8',
          times: 0
        }
      ],
```
然后`UI`回去读code，拿到关卡名然后展示在`UI`上，大概长这样
![image](https://user-images.githubusercontent.com/33803916/171037294-bbd668bf-4535-4eab-83b0-c46ec98d28a9.png)
由于支持的关卡可能会经常变动，硬编码可能不太合适，考虑比如`core`通过回调返回一个关卡支持列表? @MistEO 
然后是`CE-5/6`这种混合的关卡支持，还有剿灭，`UI`现在的结构是没法展示的，cc康康 @ChingCdesu

**Comment by MistEO** [comment]
学姐在做全关卡导航了（

**Comment by bakashigure** [comment]
> 学姐在做全关卡导航了（ @ABA2396

我 超 ！

**Comment by MistEO** [comment]
MAA 现在的架构，core 完全不知道有哪些关卡。。

单独维护一份 关卡名-关卡 code 的映射表吧，至于是 ui 维护还是 core 维护那再说（我建议 UI 维护

**Comment by bakashigure** [comment]
给`code`就行，ui 这里有全部的对照表, submodule

**Comment by MistEO** [comment]
> 给`code`就行，ui 这里有全部的对照表, submodule

我就是说 core 支持的 code 映射表，~~超这么一想还是得 core 做~~

**Comment by bakashigure** [comment]
cc之前做过一版全关卡支持的，可以搜关卡名然后添加作战的，因为`core`支持的太少就被砍掉了(

**Comment by ChingCdesu** [comment]
等core支持就上线
