### ISSUE TITLE
组件安装不来😭

### ISSUE THREAD

**Issue by maidangdang1** [MaaAssistantArknights/MaaAsstElectronUI#59]
![image](https://user-images.githubusercontent.com/46847241/187838393-3962b454-7bb5-470d-97d7-d001e4a52737.png)
用的alpha10版本，组件一直下载不下来，是需要魔法嘛 还是我依赖啥的没装好
[Maa App-20220901.log](https://github.com/MaaAssistantArknights/MaaAsstElectronUI/files/9467114/Maa.App-20220901.log)

**Comment by bakashigure** [comment]
目前下载全走的github, 所以需要魔法

**Comment by maidangdang1** [comment]
明白了🫡

**Comment by ChingCdesu** [comment]
国内的下载服务器在做了，不知道啥时候能做完(つД`)ノ
