### ISSUE TITLE
启动时报错Cannot find module 'new-github-issue-url'

### ISSUE THREAD

**Issue by wuqs-net** [MaaAssistantArknights/MaaAsstElectronUI#85]
从release页面下载v2.0.0-alpha.54版本的win64包之后在运行MaaAssistantArknights.exe的时候出现以下错误：
<img width="419" alt="image" src="https://user-images.githubusercontent.com/22854142/219995413-69e6d5c0-bf57-45e3-8485-4ec8e213e3b3.png">
请问正确的打开方式是？

**Comment by bakashigure** [comment]
旧包打包问题导致，请尝试新的 release
