### ISSUE TITLE
启动时报错: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Decem6er** [MaaAssistantArknights/MaaAsstElectronUI#88]
曾经成功启动过，但在下载安装里面的各种依赖时失败，重启软件后就这样了。重新下载安装 MaaAsstElectronUI 仍然无法解决。谢谢

![image](https://user-images.githubusercontent.com/16839570/224495677-a05a6f60-89a1-4b99-bee4-8b7295c0945f.png)

系统信息：
版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎7/‎17
操作系统版本	22621.1265
体验	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by zfh0302** [comment]
一样的

**Comment by ChingCdesu** [comment]
新版本我们移除了这个问题相关的依赖，这个无法启动的问题应该得到解决了
不开科学上网下载可能会很慢，也有很大概率出错，后面我们会使用自建服务器和镜像的方式来解决这个问题，但是现在还没有搭建好这些
